import html
import json
from pathlib import Path
from typing import Any, Dict, List

import typst


TEMPLATE_PATH = (
    Path(__file__).resolve().parent.parent / "templates" / "study_guide.typ"
)


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).replace("\\(", "").replace("\\)", "").replace("\\[", "").replace("\\]", "").strip()


def escape_typst_text(value: Any) -> str:
    text = clean_text(value)
    text = text.replace("\\", "\\")
    text = text.replace("[", "\\[").replace("]", "\\]")
    return text


def escape_typst_title(value: Any) -> str:
    return escape_typst_text(value).replace("#", "\\#")


def equation_to_typst(value: Any) -> str:
    equation = clean_text(value)
    if not equation:
        return ""

    equation = equation.replace("\\[", "").replace("\\]", "")
    equation = equation.replace("\\(", "").replace("\\)", "")
    equation = equation.strip("$ ")

    replacements = {
        "\\cdot": " dot ",
        "\\times": " times ",
        "\\pm": " plus.minus ",
        "\\leq": " <= ",
        "\\le": " <= ",
        "\\geq": " >= ",
        "\\ge": " >= ",
        "\\neq": " != ",
        "\\infty": " infinity ",
        "\\rightarrow": " arrow ",
        "\\to": " arrow ",
        "\\left": "",
        "\\right": "",
        "\\,": " ",
        "\\ ": " ",
        "\\quad": " ",
        "\\qquad": " ",
        "\\textbf": "",
        "\\mathbf": "",
        "\\mathrm": "",
        "\\text": "",
    }

    for source, target in replacements.items():
        equation = equation.replace(source, target)

    equation = equation.replace("\\frac{", "frac{")
    equation = equation.replace("\\sqrt{", "sqrt{")

    return equation.strip()


def add_text_paragraphs(lines: List[str], value: Any) -> None:
    text = clean_text(value)
    if not text:
        return

    paragraphs = [part.strip() for part in text.split("\n\n") if part.strip()]
    for paragraph in paragraphs:
        lines.append(escape_typst_text(paragraph))
        lines.append("")


def add_bullets(lines: List[str], items: Any) -> None:
    if not isinstance(items, list):
        return

    for item in items:
        text = clean_text(item)
        if text:
            lines.append(f"- {escape_typst_text(text)}")
    if items:
        lines.append("")


def build_study_guide_typst(notes: Dict[str, Any] | List[Dict[str, Any]], title: str) -> str:
    note_list = notes if isinstance(notes, list) else [notes]
    lines: List[str] = []

    lines.append(f"= {escape_typst_title(title or 'AI Study Guide')}")
    lines.append("")
    lines.append("Generated by *Note'sUp* — AI Study Guide")
    lines.append("")

    for index, note in enumerate(note_list, start=1):
        if not isinstance(note, dict):
            continue

        topic = clean_text(note.get("topic")) or "Study Topic"
        lines.append(f"= {index}. {escape_typst_title(topic)}")
        lines.append("")

        status = clean_text(note.get("status"))
        if status:
            lines.append(f"*Status:* {escape_typst_text(status)}")
            lines.append("")

        why_needed = note.get("why_needed")
        if why_needed:
            lines.append("== Why this is needed")
            lines.append("")
            add_text_paragraphs(lines, why_needed)

        student_knowledge = note.get("student_knowledge")
        if student_knowledge:
            lines.append("== What you already know")
            lines.append("")
            add_text_paragraphs(lines, student_knowledge)

        missing_information = note.get("missing_information")
        if isinstance(missing_information, list) and missing_information:
            lines.append("== Focus on these gaps")
            lines.append("")
            add_bullets(lines, missing_information)

        sections = note.get("sections")
        if isinstance(sections, list):
            for section in sections:
                if not isinstance(section, dict):
                    continue

                heading = clean_text(section.get("heading"))
                content = section.get("content")

                if heading:
                    lines.append(f"== {escape_typst_title(heading)}")
                    lines.append("")

                add_text_paragraphs(lines, content)

                equations = section.get("equations")
                if isinstance(equations, list):
                    for equation in equations:
                        rendered = equation_to_typst(equation)
                        if rendered:
                            lines.append(f"$ {rendered} $")
                            lines.append("")

        exam_points = note.get("exam_points")
        if isinstance(exam_points, list) and exam_points:
            lines.append("== Exam Points")
            lines.append("")
            add_bullets(lines, exam_points)

        sources = note.get("sources")
        if isinstance(sources, list) and sources:
            source_text = " • ".join(clean_text(source) for source in sources if clean_text(source))
            if source_text:
                lines.append(f"*Sources:* {escape_typst_text(source_text)}")
                lines.append("")

        if index < len(note_list):
            lines.append("#pagebreak()")
            lines.append("")

    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    return template.replace("{{CONTENT}}", "\n".join(lines))


def compile_study_guide_pdf(
    notes: Dict[str, Any] | List[Dict[str, Any]],
    title: str,
) -> bytes:
    source = build_study_guide_typst(notes, title)

    try:
        pdf_bytes = typst.compile(source.encode("utf-8"), format="pdf")
    except Exception as error:
        print(
            f"TYPST PDF ERROR | type={type(error).__name__} | "
            f"error={repr(error)}"
        )
        raise RuntimeError(f"Typst PDF generation failed: {error}") from error

    if not pdf_bytes:
        raise RuntimeError("Typst returned an empty PDF.")

    print(
        f"TYPST PDF SUCCESS | title={title!r} | "
        f"bytes={len(pdf_bytes)}"
    )

    return pdf_bytes
